# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 3
  - name: Contact
    url: /contact/
    weight: 10
  - name: Blog
    url: /blog/
    weight: 12
    identifier: "blog"
  - name: Drumming
    url: /categories/drumming/
    weight: 13
    parent: "blog"
  - name: Technology
    url: /categories/technology/
    weight: 14
    parent: "blog"
  - name: Musings
    url: /categories/musings/
    weight: 15
    parent: "blog"
  - name: Resume
    url: https://roumail.github.io/markdown-cv
    weight: 16
  - name: Tags
    url: /tags/  # Pointing to the new tags page
    weight: 20
