# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 3
  # - name: About
  #   url: /about/
  #   weight: 4
  - name: Contact
    url: /contact/
    weight: 10
  - name: Blog
    url: /blog/
    weight: 11
    identifier: "blog"
  - name: Resume
    url: https://roumail.github.io/markdown-cv
    weight: 16
  - name: Sitemap
    url: /sitemap/  # Pointing to the new tags page
    weight: 20
