repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0 
    hooks:
      - id: black
        name: black
        language_version: python3.9  
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0 
    hooks:
      - id: isort
        name: isort
        language_version: python3.9  
        args: ["--settings-path=pyproject.toml"]
  
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4 
    hooks:
      - id: flake8
        language_version: python3.9  