[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "website"
version = "1.0.6"
description = "Automation and build tools for my website"
authors = ["Rohail Taimour"]
license = "MIT"
packages = [
    { include = "website" },
]
dependencies = [
  "typer>=0.12.3",
]
requires-python = ">=3.10"

[project.optional-dependencies.dev]
black = ">=23.7.0"
isort = ">=5.12.0"
pre-commit = ">=3.3.3"
flake8 = ">=6.1.0"
bump2version = ">=1.0.1"
toml = ">=0.10.2"

[project.scripts]
website = "website.entrypoints:app"
new-post = 'website.entrypoints:new_post'
list-draft-posts = 'website.entrypoints:list_draft_posts'

[tool.bumpversion]
commit = true
tag = true

[[tool.bumpversion.file]]
filename = "CHANGELOG.md"
search = "## [Unreleased]"
replace = "## [Unreleased]\n\n## [{new_version}] - {now:%Y-%m-%d}"

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88