[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "website"
version = "1.1.0"
description = "Automation and build tools for my website"
authors = [
  { name = "Rohail Taimour" }
]
packages = [
  { include = "website" }
]
license = { text = "MIT License" }
dependencies = [
  "typer>=0.12.3",
]
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
  "black>=23.7.0",
  "isort>=5.12.0",
  "pre-commit>=3.3.3",
  "flake8>=6.1.0",
  "bump2version>=1.0.1"
]
[project.scripts]
website = "website.entrypoints:app"
new-post = 'website.entrypoints:new_post'
list-draft-posts = 'website.entrypoints:list_draft_posts'

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88