version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s - %(name)10s - %(levelname)-7s - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    console_color: # suited for black background
        "()": "colorlog.ColoredFormatter"
        format: "%(log_color)s%(asctime)s - %(name)10s - %(levelname)-7s - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
        reset: True
        log_colors:
        # cfr. https://github.com/borntyping/python-colorlog
        # supported colors: blue|cyan|green|yellow|red|purple|white|black
        # supported prefixes: "bold_" and "bg_"
        # <LOGLEVEL>: <foreground-color>,<background-color>
        # comma is the separator, but no extra spaces allowed
            DEBUG: cyan
            INFO: bold_green
            WARNING: yellow
            ERROR: red
            CRITICAL: purple


handlers:
    console:
        class: logging.StreamHandler
        formatter: console_color
        level: INFO  # Keep console rather clear
        stream: ext://sys.stdout

    debug_file:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        level: DEBUG
        filename: "{LOG_DIR}/debug.log"
        maxBytes: 10485760 # 10 MB
        backupCount: 5

    info_file:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        level: INFO
        filename: "{LOG_DIR}/info.log"
        maxBytes: 10485760 # 10 MB
        backupCount: 5

    error_file:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        level: ERROR
        filename: "{LOG_DIR}/error.log"
        maxBytes: 10485760 # 10 MB
        backupCount: 5

root:
    level: DEBUG
    handlers:
        - console
        - debug_file
        - info_file
        - error_file

loggers:
    urllib3:
        level: WARNING
        handlers:
            - console