name: Deploy to Github Pages

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: r-lib/actions/setup-pandoc@v2
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.3
        use-public-rspm: true
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        Rscript -e "install.packages(c('blogdown'))"
    
    - name: Set HUGO_VERSION as env variable
      run: echo "HUGO_VERSION=$(jq -r '.build.env.HUGO_VERSION' vercel.json)" >> $GITHUB_ENV

    - name: Install Hugo
      run: blogdown::install_hugo(Sys.getenv("HUGO_VERSION"))
      shell: Rscript {0}
      
    - name: Build site
      run:  |
        Rscript -e "blogdown::build_site(local = FALSE)"
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_branch: gh-pages
        publish_dir: ./public
