name: Deploy to Github Pages

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run RStudio Docker image
      run: |
        docker run -v $PWD:/home/rstudio -w /home/rstudio rocker/rstudio:4.3 bash -c 'apt-get update && apt-get install -y jq; Rscript R/build.R'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
