name: Deploy to Github Pages

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: r-lib/actions/setup-pandoc@v2
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.3
        use-public-rspm: true
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    
    - name: Install Hugo
      run: |
        hugo_version=$(jq -r '.build.env.HUGO_VERSION' vercel.json)
        Rscript -e "blogdown::install_hugo(version = '${hugo_version}')"

    - name: Build site
      run:  |
        Rscript -e "blogdown::build_site(local = FALSE)"
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
