name: Deploy to Github Pages

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: 4.3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq        
    
    - name: Build site
      run: Rscript R/build.R    
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
