name: Deploy to Github Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Set HUGO_VERSION as env variable
      run: echo "HUGO_VERSION=$(jq -r '.build.env.HUGO_VERSION' vercel.json)" >> $GITHUB_ENV

    - name: Install Hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
        sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
      
    - name: Build site
      run: hugo
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_branch: gh-pages
        publish_dir: ./public
