name: Release Website Package

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install poetry
        pip install keepachangelog@git+https://github.com/Colin-b/keepachangelog

    - name: Get package version via Poetry
      run: |
        PACKAGE_VERSION=$(poetry version -s)
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
    
    - name: Get changelog body
      run: |
        CHANGELOG_BODY=$(keepachangelog show ${{ env.PACKAGE_VERSION }})
        echo "CHANGELOG_BODY=$CHANGELOG_BODY" >> $GITHUB_ENV
    
    - name: Build Package
      run: poetry build
    
    - name: Tag Release
      run: |
        git tag v${{ env.PACKAGE_VERSION }}
        git push origin v${{ env.PACKAGE_VERSION }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*.tar.gz"
        body: ${{ env.CHANGELOG_BODY }}
        token: ${{ secrets.GH_PAT }}
