name: Release Website Package

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install poetry
        pip install keepachangelog@git+https://github.com/Colin-b/keepachangelog

    - name: Get package version and changelog body
      run: |
        PACKAGE_VERSION=$(poetry version -s)
        keepachangelog show $PACKAGE_VERSION > changelog_body.txt
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
        
    
    - name: Build Package
      run: poetry build
    
    - name: Check if tag exists
      id: check_tag
      run: |
        if git rev-parse ${{ env.PACKAGE_VERSION }} >/dev/null 2>&1; then
          echo "Tag exists!"
          echo "TAG_EXISTS=true" >> $GITHUB_ENV
        else
          echo "Tag does not exist."
          echo "TAG_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Tag Release
      if: env.TAG_EXISTS == 'false'
      run: |
        git tag v${{ env.PACKAGE_VERSION }}
        git push origin v${{ env.PACKAGE_VERSION }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*.tar.gz"
        bodyFile: changelog_body.txt
        token: ${{ secrets.GH_PAT }}
    
    - name: Cleanup
      run: rm changelog_body.txt
